#!/bin/bash

## Description: Run PHPCBF commands within the DDEV web container
## Usage: phpcbf <path-to-fix> [flags]
## Example: "ddev phpcbf web/custom/my-module"

# Abort if anything fails
set -e

# Execute phpcs command with all passed arguments
./vendor/bin/phpcbf "$@"
